### ISSUE TITLE
Threading not supported on pyfftw 0.13.1

### ISSUE THREAD

**Issue by calum-chamberlain** [conda-forge/pyfftw-feedstock#59]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I ran into an issue using pyfftw 0.13.1 from conda-forge when trying to use threads. This was previously (and is currently) working with pyfftw 0.12.

The error is:
```python
>>> import numpy as np
>>> from pyfftw.interfaces.numpy_fft import rfftn
>>> arr = np.random.randn(86400)
>>> rfftn(arr, threads=2) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chambeca/miniconda3/envs/pyfftw-threaded/lib/python3.11/site-packages/pyfftw/interfaces/numpy_fft.py", line 286, in rfftn
    threads = _default_threads(threads)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chambeca/miniconda3/envs/pyfftw-threaded/lib/python3.11/site-packages/pyfftw/builders/_utils.py", line 114, in _default_threads
    raise ValueError("threads > 1 requested, but pyFFTW was not built "
ValueError: threads > 1 requested, but pyFFTW was not built with multithreaded FFTW.
```

I replicated this in a fresh environment created using:
```bash
conda create -n pyfftw-threaded -c conda-forge pyfftw
```

Creating a similar fresh environment with `pyfftw==0.12` does not result in the error.

I'm running into this error across all operating systems and python 3.[8-11] in tests [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=670212&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412) associated with [this PR](https://github.com/conda-forge/eqcorrscan-feedstock/pull/45)

### Installed packages

```shell
# packages in environment at /home/chambeca/miniconda3/envs/pyfftw-threaded:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.24.2          py311h8e6699e_0    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pyfftw                    0.13.1          py311hcb2cf0a_0    conda-forge
python                    3.11.0          he550d4f_1_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                67.5.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : pyfftw-threaded
    active env location : /home/chambeca/miniconda3/envs/pyfftw-threaded
            shell level : 3
       user config file : /home/chambeca/.condarc
 populated config files : /home/chambeca/.condarc
          conda version : 22.11.1
    conda-build version : 3.21.9
         python version : 3.9.15.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.37=0
                          __linux=5.15.94=0
                          __unix=0=0
       base environment : /home/chambeca/miniconda3  (writable)
      conda av data dir : /home/chambeca/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/chambeca/miniconda3/pkgs
                          /home/chambeca/.conda/pkgs
       envs directories : /home/chambeca/miniconda3/envs
                          /home/chambeca/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.15 Linux/5.15.94-1-MANJARO manjaro/22.0.4 glibc/2.37
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by ax3l** [comment]
I see a similar issue downstream in https://github.com/conda-forge/fbpic-feedstock/pull/1

Can you enable threading for pyFFTW?

https://github.com/pyFFTW/pyFFTW/issues/294

**Comment by ax3l** [comment]
I think there is an inconsistency on Linux/macOS.
Upstream `fftw-static` is build with OpenMP, not threads:
https://github.com/conda-forge/fftw-feedstock/blob/e3fcf707566c5d71f7302ff4943eb0a4006e1bcb/recipe/build_fftw.sh#L18

but the feedstock here uses threads, not OpenMP:
https://github.com/conda-forge/pyfftw-feedstock/blob/6b0c1880fc91742f98c6aec6e69ee7838324e647/recipe/build.sh#L8-L9

**Comment by jakirkham** [comment]
When OpenMP was added to FFTW, it was our understanding that pthreads support would remain ( https://github.com/conda-forge/fftw-feedstock/pull/46#issuecomment-442564040 ), 
the flag in PyFFTW is intended to use pthreads ( https://github.com/conda-forge/pyfftw-feedstock/pull/29 )

The static library [should include threads support]( https://github.com/conda-forge/fftw-feedstock/blob/e3fcf707566c5d71f7302ff4943eb0a4006e1bcb/recipe/meta.yaml#L181-L183 ) too

Am guessing there is something else going on

**Comment by karlotness** [comment]
I think this is due to failures in the test builds to detect the FFTW+pthreads static libraries. That causes the extension to build without any threading support leading to the errors. I think #60 *should* fix that problem.

**Comment by paugier** [comment]
Finally fixed by https://github.com/conda-forge/pyfftw-feedstock/pull/60!
